refactored pynumerals from channumerals; improved tests
numeralbank/pynumerals pull request #1
Opened 2020-07-03 12:40 UTC by Bibiko

2020-07-03 19:38 UTC, chrzyki approved these changes
Looks good, thanks!

2020-07-06 10:01 UTC, xrotwang requested changes
Please move the package directory into a `src` directory to make sure testing via `tox` can reveal packaging problems, too.

2020-07-06 10:01 UTC, xrotwang commented on setup.cfg
> +source = pynumerals
Please include the `tests` directory in the coverage report. This makes sure we don't accumulate stale/obsolete/nut-run tests.

2020-07-06 10:01 UTC, xrotwang commented on setup.py
> +        'pytest',
`pytest` is only required to run tests, right? So it should be required as `extra`, see e.g. https://github.com/pofatu/pygeoroc/blob/cd0d249aeb43c33222d452bc57a9f64b06a82714/setup.py#L37-L46

2020-07-06 10:19 UTC, xrotwang approved these changes

2020-07-06 10:21 UTC, merged